PurpleStore/urls.py
from django.contrib import admin
from django.urls import path, include  # new
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('thestore.urls')),
]

# if settings.DEBUG:
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thestore/urls.py
from django.urls import path
from . import views

app_name = 'thestore'

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
]

thestore/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

# Customer model
class Customer(models.Model):
    user = models.OneToOneField(User, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)

    def __str__(self):
        return self.name


# Product model
class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    # error handling for images with no url, @property decorator allows us to call this method like an attribute e.g product.imageURL
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


# An order compilation of all order_items
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True, related_name='orders')
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        order_items = self.order_items.all()
        total = sum([item.get_total for item in order_items])
        return total

    @property
    def get_cart_quantity(self):
        order_items = self.order_items.all()
        total = sum([item.quantity for item in order_items])
        return total


# Items in the order cart
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True,
                                related_name='products_ordered')
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True, related_name='order_items')
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.product.name)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


# Shipping address
class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True,
                                 related_name='shipping_customer')
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True, related_name='shipping_order')
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

thestore/views.py
from django.shortcuts import render
from .models import *


# Create your views here.


def store(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'thestore/store.html', context)


def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        # gets the order render to the order var or creates a new one if it doesn't exist render to the created var
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.order_items.all()
    else:
        items = {}
        order = {'get_cart_total': 0, 'get_cart_quantity': 0}

    context = {'items': items, 'order': order}
    return render(request, 'thestore/cart.html', context)


def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        # gets the order render to the order var or creates a new one if it doesn't exist render to the created var
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.order_items.all()
    else:
        items = {}
        order = {'get_cart_total': 0, 'get_cart_quantity': 0}
    context = {'items': items, 'order': order}
    return render(request, 'thestore/checkout.html', context)

thestore/templates/thestore/cart.html
{% extends 'thestore/main.html' %}
{% load static %}


{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a class='btn btn-outline-dark' href="{%url 'thestore:store'%}">Continue Shopping</a>
                <br> <br>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{order.get_cart_quantity}}</strong></h5></th>
                        <th><h5>Total: <strong>${{order.get_cart_total|floatformat:2}}</strong></h5></th>
                        <th>
                            <a style="float: right" class="btn btn-success" href="{%url 'thestore:checkout' %}">
                                Checkout <i class="fa fa-chevron-right"></i>
                            </a>
                        </th>

                    </tr>
                </table>
            </div>
            <br>
              <div class="box-element">
                  <div class="cart-row">
                     <div style="flex:2"></div>
                     <div style="flex:2"><strong>Item</strong></div>
                     <div style="flex:1"><strong>Price</strong></div>
                     <div style="flex:1"><strong>Quantity</strong></div>
                     <div style="flex:1"><strong>Total</strong></div>

                  </div>

                  {%for item in items %}
                  <div class="cart-row">
                      <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}" ></div>
                     <div style="flex:2"><p>{{item.product.name}}</p></div>
                     <div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
                     <div style="flex:1">
                         <p class="quantity">{{item.quantity}}</p>
                         <div class="quantity">
                             <img class="chg-quantity" src="{%static 'images/arrow-up.png'%}">
                             <img class="chg-quantity" src="{%static 'images/arrow-down.png'%}">
                         </div>
                     </div>

                      <div style="flex:1"><p>${{item.get_total}}</p></div>
                  </div>


            {% endfor %}
   </div>
        </div>
    </div>
{% endblock content %}

thestore/templates/thestore/checkout.html
{% extends 'thestore/main.html' %}
{% load static %}

{% block content %}
<div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>

					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>

					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
			</div>
        </div>

   <div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'thestore:cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
<!--				<div class="cart-row">-->
<!--					<div style="flex:2"><img class="row-image" src="{% static 'images/placeholder.png' %}"></div>-->
<!--					<div style="flex:2"><p>Product 1</p></div>-->
<!--					<div style="flex:1"><p>$20.00</p></div>-->
<!--					<div style="flex:1"><p>x2</p></div>-->
<!--				</div>-->
				     {%for item in items %}
                  <div class="cart-row">
                      <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}" ></div>
                     <div style="flex:2"><p>{{item.product.name}}</p></div>
                     <div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
                     <div style="flex:1">
                         <p class="quantity">{{item.quantity}}</p>
                         <div class="quantity">
                             <img class="chg-quantity" src="{%static 'images/arrow-up.png'%}">
                             <img class="chg-quantity" src="{%static 'images/arrow-down.png'%}">
                         </div>
                     </div>

                      <div style="flex:1"><p>${{item.get_total}}</p></div>
                  </div>

            {% endfor %}
				<h5>Items:   {{order.get_cart_quantity}}</h5>
				<h5>Total:   ${{order.get_cart_total|floatformat:2}}</h5>
			</div>
		</div>
	</div>

{% endblock content %}

thestore/templates/thestore/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Hello world</h1>
</body>
</html>

thestore/templates/thestore/main.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content= "width=device-width", initial-scale=1, maximum-scale=1, minimum-scale=1"/>
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel ='stylesheet' href="{%static 'css/main.css'%}" type='text/css'></link>
    <title>PurpleStore</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="nav_bar_theme">
	  <a class="navbar-brand" href="{%url 'thestore:store' %}">PurpleBuy</a>
    <button id="theme-changer" style="border:none; background-color:#7A4DE0">
     <img width="30" height="30" src="https://img.icons8.com/ios/50/light-on--v1.png" alt="light-on--v1" />
    </button>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		  <ul class="navbar-nav mr-auto">
	     	<li class="nav-item active">
				<a class="nav-link" href="{%url 'thestore:store' %}"></a>
			</li>
	    </ul>

	    <div class="form-inline my-2 my-lg-0">
	     <a href ="#" class="btn btn-warning">Login</a>
	     <a href ="{%url 'thestore:cart' %}" >
<!--			 https://img.icons8.com/ios/50/000000/shopping-cart.png"-->
			 	     	<img src="{%static 'images/cart.png'%}" alt="shopping-cart" id="cart-icon" width="30" height="30"/>
		 </a>
			<p id="cart-total">0</p>

	    </div>
	  </div>
	</nav>


    <div class="container">
        <br>
        {% block content %}

        {% endblock content %}
    </div>


    <script src="{% static 'js/theme_changer.js' %}" ></script>
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

thestore/templates/thestore/store.html
{% extends 'thestore/main.html' %}
{% load static %}

{% block content %}
    <div class="row">
        {% if products %}
        {% for product in products %}
          <div class="col-lg-4">
        {% if product.imageURL %}
        <img class="thumbnail" src="{{product.imageURL}}">
              {% else %}
<!--              if not image, use placeholder-->
<img class="thumbnail" src="{% static 'images/placeholder.png'%}">
              {% endif %}

            <div class="box-element product">
                <h6><strong>{{product.name}}</strong></h6>
                <hr>
                <button  class="btn btn-outline-secondary add-btn">Add to Cart</button>
				<a class="btn btn-outline-success" href="#">View</a>
				<h5 style="display: inline-block; float: right">
                    <strong>${{product.price|floatformat:2}}</strong></h5>
            </div>
        </div>
        {% endfor %}
        {% else %}

<!--        Placeholder for products-->
                            <div class="col-lg-4">
        <img class="thumbnail" src="{% static 'images/placeholder.png'%}">
            <div class="box-element product">
                <h6><strong>Product</strong></h6>
                <hr>
                <button  class="btn btn-outline-secondary add-btn">Add to Cart</button>
				<a class="btn btn-outline-success" href="#">View</a>
				<h4 style="display: inline-block; float: right"><strong>$20</strong></h4>
            </div>
        </div>
        <div class="col-lg-4">
        <img class="thumbnail" src="{% static 'images/placeholder.png'%}">
            <div class="box-element product">
                 <h6><strong>Product</strong></h6>
                <hr>
                <button  class="btn btn-outline-secondary add-btn">Add to Cart</button>
				<a class="btn btn-outline-success" href="#">View</a>
				<h4 style="display: inline-block; float: right"><strong>$20</strong></h4>
            </div>

        </div>

        <div class="col-lg-4">
        <img class="thumbnail" src="{% static 'images/placeholder.png'%}">
            <div class="box-element product">
                 <h6><strong>Product</strong></h6>
                <hr>
                <button  class="btn btn-outline-secondary add-btn">Add to Cart</button>
				<a class="btn btn-outline-success" href="#">View</a>
				<h4 style="display: inline-block; float: right"><strong>$20</strong></h4>
            </div>
        </div>
            </div>
        {% endif %}

{% endblock content %}